/** A consent-first subscriber form for journal release notifications. */
import { Check, Loader2, MailPlus } from "lucide-react";
import { type FormEvent, useState } from "react";
import { trpc } from "@/lib/trpc";

export function SubscribeForm() {
  const [email, setEmail] = useState("");
  const [displayName, setDisplayName] = useState("");
  const [consent, setConsent] = useState(false);
  const subscribe = trpc.editorial.subscribe.useMutation({ onSuccess: () => { setEmail(""); setDisplayName(""); setConsent(false); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); subscribe.mutate({ email, displayName: displayName || undefined, consent: true }); };
  if (subscribe.isSuccess) return <div className="border border-[#b78a58]/50 bg-[#11100f] p-5"><Check size={17} className="text-[#b78a58]" /><p className="mt-4 font-display text-2xl text-[#f3f0ea]">You’re on the list.</p><p className="mt-2 text-sm leading-relaxed text-[#aaa69f]">We’ll keep the next journal note close to the source.</p><button type="button" onClick={() => subscribe.reset()} className="mt-4 font-mono text-[0.56rem] uppercase tracking-[0.13em] text-[#b78a58]">Subscribe another address</button></div>;
  return <form onSubmit={submit} className="grid gap-3" aria-label="Subscribe to new journal notes"><label className="grid gap-1.5"><span className="font-mono text-[0.55rem] uppercase tracking-[0.14em] text-[#99948c]">Name <span className="normal-case tracking-normal">(optional)</span></span><input value={displayName} onChange={(event) => setDisplayName(event.target.value)} className="h-10 border-b border-white/20 bg-transparent px-0 text-sm text-[#f3f0ea] outline-none transition-colors placeholder:text-[#625f59] focus:border-[#b78a58]" placeholder="Your name" /></label><label className="grid gap-1.5"><span className="font-mono text-[0.55rem] uppercase tracking-[0.14em] text-[#99948c]">Email</span><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="h-10 border-b border-white/20 bg-transparent px-0 text-sm text-[#f3f0ea] outline-none transition-colors placeholder:text-[#625f59] focus:border-[#b78a58]" placeholder="you@example.com" /></label><label className="mt-1 flex items-start gap-2 text-xs leading-relaxed text-[#aaa69f]"><input required type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-0.5 accent-[#b78a58]" /><span>I agree to receive new journal notes. I can unsubscribe at any time.</span></label>{subscribe.error ? <p className="font-mono text-[0.56rem] text-[#e08a76]">{subscribe.error.message}</p> : null}<button type="submit" disabled={subscribe.isPending || !consent} className="mt-2 inline-flex w-fit items-center gap-2 border-b border-[#b78a58]/80 pb-2 font-mono text-[0.58rem] uppercase tracking-[0.13em] text-[#f3f0ea] transition-colors hover:border-[#f3f0ea] disabled:cursor-not-allowed disabled:opacity-50">{subscribe.isPending ? <Loader2 size={14} className="animate-spin text-[#b78a58]" /> : <MailPlus size={14} className="text-[#b78a58]" />} {subscribe.isPending ? "Saving" : "Subscribe to notes"}</button></form>;
}
